version: "3"
services:
  wordpress:
    image: "library/wordpress:latest"
    ports:
      - "8080:80"
    environment:
      - "WORDPRESS_DB_HOST=mariadb"
      - "WORDPRESS_DB_USER=mariadb"
      - "WORDPRESS_DB_PASSWORD=123123"
      - "WORDPRESS_DB_NAME=jmi"
    depends_on:
      - "mariadb"
    volumes:
      - "wordpress:/var/www/html"
  mariadb:
    image: "library/mariadb:latest"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=123123"
      - "MYSQL_DATABASE=jmi"
      - "MYSQL_USER=mariadb"
      - "MYSQL_PASSWORD=123123"
    volumes:
      - "database:/var/lib/mysql"
volumes:
  database:
  wordpress:
